#104 append toi mdib report retrofit
IHE/sdpi-fhir pull request #176
Opened 2022-10-26 14:14 UTC by riechkathrin

2022-10-27 15:36 UTC, JavierEspina commented
_R1007: "Messages (expect for Discovery messages) send between a <<actor_somds_consumer>> and a <<actor_somds_provider>> SHALL be sent via HTTP."
Didn't I make a mistake in the Luebeck minutes (that has propagated through) by writing HTTP? I think we actually meant TCP.
Moreover the first verb should be in past tense.
Proposed rephrase: "_Messages (expect for Discovery messages) sent between a <<actor_somds_consumer>> and a <<actor_somds_provider>> SHALL be sent via a TCP connection."

2022-10-27 15:42 UTC, JavierEspina commented
I think the note under R1008 should be moved out of that requirement box, as it applies to all 8 requirements in the section.
Also the note text (admittedly mine... created while typing minutes in real time) could be made a bit more precise / formal...

2022-10-28 13:10 UTC, JavierEspina requested changes
see last commit (by me) with the changes proposed above and feel free to roll them back, accept them or add on top of them

2022-11-02 16:00 UTC, JavierEspina reviewed
The changes requested earlier have been incorporated with the last commits. With that, it looks good to me. I propose that David does the final check and, if he sees no further issues, feels free to accept the PR.

2022-11-03 07:16 UTC, d-gregorczyk commented on SDPi_Supplement/asciidoc/volume3/mdib-report-retrofit/tf3-ch-8.2.8-mdib-report-retrofit.adoc
> +NOTE: Replaces biceps:R5024: "Descriptors in this list shall not include nested descriptors."
As this cites the BICEPS standard, shall is deliberately written in capitals
```suggestion
NOTE: Replaces biceps:R5024: "Descriptors in this list SHALL not include nested descriptors."

```

2022-11-03 07:24 UTC, d-gregorczyk approved these changes

2022-11-03 07:29 UTC, d-gregorczyk approved these changes

2022-11-03 07:33 UTC, merged